In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
x = np.array([[1.,-1., 2.],[2., 0., 0.],[0., 1., -1.]])

In [4]:
x_scaled = preprocessing.scale(x)    #it makes mean to be 0 and variance to be 1 .... centres data towards centre

In [5]:
x_scaled.mean(axis=0)

array([0., 0., 0.])

In [6]:
x_scaled.std(axis=0)

array([1., 1., 1.])

Limitations of scale function:
1. Assumes normal distribution.
2. 
Sensitive to outliers.3. 
Loss of interpretability4. .
Inefficient with sparse dat5. a.
Modifies original da6. ta.
Limited to numeric d7. ata.
Requires manual tuning of parameters.

In [7]:
scaler = preprocessing.StandardScaler()
scaler.fit(x)

scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [9]:
x_test = [[1,1,0]]
scaler.transform(x_test)
#it scales this testing data on the basis of our training data x

array([[ 0.        ,  1.22474487, -0.26726124]])